### ISSUE TITLE
Syllabic stress in CLTS system?

### ISSUE THREAD

**Issue by Anaphory** [clpn/clpa#46]
I just hacked a bit looking at the possibility of using CLTS features for the binary features in `zounds` (https://github.com/ajenhl/zounds). In doing that, I noticed that I could not find any traces of syllabic stress (`ˈ`, `ˌ`) in CLTS. Is that by design or did they just get lost somewhere?

**Comment by LinguList** [comment]
syllabic stress belongs to the sound sequence, while clts is working with sounds in isolation. We're currently thinking of how to regularly include things into the CLDF, but will have to wait until we find time. Closing this for now, as it is not a target priority, as far as we have not even yet decided on how to implement the new CLTS.
