### ISSUE TITLE
Windows assumes 'README.md' is in Windows-standard encoding 

### ISSUE THREAD

**Issue by Cryotops** [clpn/clpa#47]
The read()-function of 'setup.py' uses default encoding. This causes a problem under Windows-standard encoding when reading the 'README.md', because it contains special characters. Subsequently, installing the package fails.

A patch is coming in a moment.

**Comment by LinguList** [comment]
Hi, please not that this repository is deprecated! We don't work on it anymore, instead, we have a new version which is currently not publicly available, but if you write me an email, I can give you access. The demo of this version, which is much better than the older, is here: http://calc.digling.org/clts/
